name: Trigger auto deployment for container-app-tqqd4yu4yqwxw

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-tqqd4yu4yqwxw-AutoDeployTrigger-36ffbc5e-af12-4b48-9f7b-89dcba3ff41a.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPTQQD4YU4YQWXW_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPTQQD4YU4YQWXW_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPTQQD4YU4YQWXW_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPTQQD4YU4YQWXW_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPTQQD4YU4YQWXW_REGISTRY_PASSWORD }}
          containerAppName: container-app-tqqd4yu4yqwxw
          resourceGroup: todonodejspgsqlgoogleauth97889034
          imageToBuild: default/container-app-tqqd4yu4yqwxw:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


